<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('instalacaofisica', function (Blueprint $table) {
            $table->id();

            $table->string('nomedep');
            $table->string('de');
            $table->string('mun');
            $table->string('distr');
            $table->string('codesc');
            $table->string('nomesc');
            $table->unsignedBigInteger('tipoesc');
            $table->string('tipoesc_desc');
            $table->string('codsit');
            $table->unsignedBigInteger('salas_aula');
            $table->unsignedBigInteger('salas_ed_inf');
            $table->unsignedBigInteger('salas_ed_esp');
            $table->unsignedBigInteger('salas_ed_art');
            $table->unsignedBigInteger('sala_recurso');
            $table->unsignedBigInteger('tot_salas_aula');
            $table->unsignedBigInteger('auditorio');
            $table->unsignedBigInteger('anfiteatro');
            $table->unsignedBigInteger('teatro');
            $table->unsignedBigInteger('cantina');
            $table->unsignedBigInteger('copa');
            $table->unsignedBigInteger('cozinha');
            $table->unsignedBigInteger('refeitorio');
            $table->unsignedBigInteger('deposito_alimentos');
            $table->unsignedBigInteger('despensa');
            $table->unsignedBigInteger('tot_despensa');
            $table->unsignedBigInteger('sala_leitura');
            $table->unsignedBigInteger('biblioteca');
            $table->unsignedBigInteger('tot_sala_leitura');
            $table->unsignedBigInteger('quadra_coberta');
            $table->unsignedBigInteger('quadra_descoberta');
            $table->unsignedBigInteger('ginasio');
            $table->unsignedBigInteger('tot_quadra');
            $table->unsignedBigInteger('quadra_areia');
            $table->unsignedBigInteger('quadra_grama');
            $table->unsignedBigInteger('campo_futebol');
            $table->unsignedBigInteger('gabinete_dentario');
            $table->unsignedBigInteger('consultorio_medico');
            $table->unsignedBigInteger('enfermaria');
            $table->unsignedBigInteger('ambulatorio');
            $table->unsignedBigInteger('almoxarifado');
            $table->unsignedBigInteger('arquivo');
            $table->unsignedBigInteger('reprografia');
            $table->unsignedBigInteger('sala_gremio');
            $table->unsignedBigInteger('diretoria');
            $table->unsignedBigInteger('vicediretoria');
            $table->unsignedBigInteger('sala_prof');
            $table->unsignedBigInteger('secretaria');
            $table->unsignedBigInteger('sala_orient_ed');
            $table->unsignedBigInteger('sala_coord_pedag');
            $table->unsignedBigInteger('patio_coberto');
            $table->unsignedBigInteger('patio_descoberto');
            $table->unsignedBigInteger('zeladoria');
            $table->unsignedBigInteger('vestiario_fem');
            $table->unsignedBigInteger('vestiario_masc');
            $table->unsignedBigInteger('tot_vestiario');
            $table->unsignedBigInteger('videoteca');
            $table->unsignedBigInteger('sala_tv');
            $table->unsignedBigInteger('lab_info');
            $table->unsignedBigInteger('lab_ciencias');
            $table->unsignedBigInteger('lab_fisica');
            $table->unsignedBigInteger('lab_quimica');
            $table->unsignedBigInteger('lab_biologia');
            $table->unsignedBigInteger('lab_ciencia_fisica_biologica');
            $table->unsignedBigInteger('tot_lab_ciencia');
            $table->unsignedBigInteger('lab_linguas');
            $table->unsignedBigInteger('lab_multiuso');
            $table->unsignedBigInteger('oficina');
            $table->unsignedBigInteger('playground');
            $table->unsignedBigInteger('dormitorio');
            $table->unsignedBigInteger('bercario');
            $table->unsignedBigInteger('sanitario_adeq_pre');
            $table->unsignedBigInteger('sanitario_adeq_pre_fem');
            $table->unsignedBigInteger('sanitario_adeq_pre_masc');
            $table->unsignedBigInteger('sanitario_adeq_def');
            $table->unsignedBigInteger('sanitario_adeq_def_fem');
            $table->unsignedBigInteger('sanitario_adeq_def_masc');
            $table->unsignedBigInteger('sanitario_al_masc');
            $table->unsignedBigInteger('sanitario_al_fem');
            $table->unsignedBigInteger('tot_sanitario_al');
            $table->unsignedBigInteger('sanitario_func_fem');
            $table->unsignedBigInteger('sanitario_func_masc');
            $table->unsignedBigInteger('tot_sanitario_func');
            $table->unsignedBigInteger('depend_adeq_def');
            $table->unsignedBigInteger('sala_ed_fisica');
            $table->unsignedBigInteger('piscina');
            $table->unsignedBigInteger('portaria');
            $table->unsignedBigInteger('sala_prog_esc_familia');
            $table->unsignedBigInteger('brinquedoteca');
            $table->unsignedBigInteger('fraldario');
            $table->unsignedBigInteger('lactario');
            $table->unsignedBigInteger('lavanderia');
            $table->unsignedBigInteger('solario');
            $table->unsignedBigInteger('sala_espera');
            $table->unsignedBigInteger('sala_inspetor');
            $table->unsignedBigInteger('sala_reuniao');
            $table->unsignedBigInteger('tesouraria');
            $table->unsignedBigInteger('sala_reforco');
            $table->unsignedBigInteger('sala_diretor_tecnico');
            $table->unsignedBigInteger('garagem_onibus');
            $table->unsignedBigInteger('sala_fisioterapia');
            $table->unsignedBigInteger('sala_psicologia');
            $table->unsignedBigInteger('sala_fonoaudiologia');
            $table->unsignedBigInteger('sala_eventos');
            $table->unsignedBigInteger('sala_assist_social');
            $table->unsignedBigInteger('sala_terapia_educ');
            $table->unsignedBigInteger('abatedouro');
            $table->unsignedBigInteger('alojamento_fem');
            $table->unsignedBigInteger('alojamento_masc');
            $table->unsignedBigInteger('tot_alojamento');
            $table->unsignedBigInteger('area_servico');
            $table->unsignedBigInteger('bazar');
            $table->unsignedBigInteger('casa_maquina');
            $table->unsignedBigInteger('casa_func');
            $table->unsignedBigInteger('churrasqueira');
            $table->unsignedBigInteger('depositos_cereais');
            $table->unsignedBigInteger('elevador');
            $table->unsignedBigInteger('estacionamento');
            $table->unsignedBigInteger('estufa');
            $table->unsignedBigInteger('galpao_aves_corte');
            $table->unsignedBigInteger('galpao_aves_postura');
            $table->unsignedBigInteger('galpao_bovinos_leite');
            $table->unsignedBigInteger('galpao_cunicultura');
            $table->unsignedBigInteger('galpao_maq_agricola');
            $table->unsignedBigInteger('galpao_ovinos_caprinos');
            $table->unsignedBigInteger('galpao_suino');
            $table->unsignedBigInteger('grafica');
            $table->unsignedBigInteger('horta');
            $table->unsignedBigInteger('lab_didatica');
            $table->unsignedBigInteger('lab_junior');
            $table->unsignedBigInteger('lab_enfermagem');
            $table->unsignedBigInteger('lab_estetica');
            $table->unsignedBigInteger('lab_psicopedagogia');
            $table->unsignedBigInteger('lab_turismo');
            $table->unsignedBigInteger('lavatorio');
            $table->unsignedBigInteger('mangueira');
            $table->unsignedBigInteger('minhocario');
            $table->unsignedBigInteger('packing_house');
            $table->unsignedBigInteger('pomar');
            $table->unsignedBigInteger('psicultura');
            $table->unsignedBigInteger('recepcao');
            $table->unsignedBigInteger('sala_atendimento');
            $table->unsignedBigInteger('sala_atend_psicologico');
            $table->unsignedBigInteger('sala_aux_coordenacao');
            $table->unsignedBigInteger('sala_dados');
            $table->unsignedBigInteger('sala_dep_pessoal');
            $table->unsignedBigInteger('sala_ed_religiosa');
            $table->unsignedBigInteger('sala_energia_eletrica');
            $table->unsignedBigInteger('sala_entretenimento');
            $table->unsignedBigInteger('sala_estagio');
            $table->unsignedBigInteger('sala_ginastica');
            $table->unsignedBigInteger('sala_insumo_agricola');
            $table->unsignedBigInteger('sala_insumo_veterinario');
            $table->unsignedBigInteger('sala_marketing');
            $table->unsignedBigInteger('sala_matricula');
            $table->unsignedBigInteger('sala_musica');
            $table->unsignedBigInteger('sala_pos_graduacao');
            $table->unsignedBigInteger('sala_ordenha');
            $table->unsignedBigInteger('sala_proc_prod_agropecuarios');
            $table->unsignedBigInteger('sala_seguranca');
            $table->unsignedBigInteger('sala_telefonia');
            $table->unsignedBigInteger('sala_financeiro');
            $table->unsignedBigInteger('sala_pastoral');
            $table->unsignedBigInteger('sala_reserv_agua');
            $table->unsignedBigInteger('servidor');
            $table->unsignedBigInteger('silo');
            $table->unsignedBigInteger('varanda');
            $table->unsignedBigInteger('viveiro');
            $table->unsignedBigInteger('sala_reorg_neuro');
            $table->unsignedBigInteger('sala_terapia_ocup');
            $table->unsignedBigInteger('sala_serigrafia');
            $table->unsignedBigInteger('sala_marcenaria');
            $table->unsignedBigInteger('quiosque');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('instalacaofisica');
    }
};
