<?php

namespace App\Imports;

use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithChunkReading;
use App\Models\InstalacaoFisica;

class InstalacaoFisicaImport implements ToModel, WithHeadingRow, WithChunkReading
{
    public function model(array $row)
    {
        return new InstalacaoFisica([
            'nomedep' => $row['nomedep'],
            'de' => $row['de'],
            'mun' => $row['mun'],
            'distr' => $row['distr'],
            'codesc' => $row['codesc'],
            'nomesc' => $row['nomesc'],
            'tipoesc' => $row['tipoesc'],
            'tipoesc_desc' => $row['tipoesc_desc'],
            'codsit' => $row['codsit'],
            'salas_aula' => $row['salas_aula'],
            'salas_ed_inf' => $row['salas_ed_inf'],
            'salas_ed_esp' => $row['salas_ed_esp'],
            'salas_ed_art' => $row['salas_ed_art'],
            'sala_recurso' => $row['sala_recurso'],
            'tot_salas_aula' => $row['tot_salas_aula'],
            'auditorio' => $row['auditorio'],
            'anfiteatro' => $row['anfiteatro'],
            'teatro' => $row['teatro'],
            'cantina' => $row['cantina'],
            'copa' => $row['copa'],
            'cozinha' => $row['cozinha'],
            'refeitorio' => $row['refeitorio'],
            'deposito_alimentos' => $row['deposito_alimentos'],
            'despensa' => $row['despensa'],
            'tot_despensa' => $row['tot_despensa'],
            'sala_leitura' => $row['sala_leitura'],
            'biblioteca' => $row['biblioteca'],
            'tot_sala_leitura' => $row['tot_sala_leitura'],
            'quadra_coberta' => $row['quadra_coberta'],
            'quadra_descoberta' => $row['quadra_descoberta'],
            'ginasio' => $row['ginasio'],
            'tot_quadra' => $row['tot_quadra'],
            'quadra_areia' => $row['quadra_areia'],
            'quadra_grama' => $row['quadra_grama'],
            'campo_futebol' => $row['campo_futebol'],
            'gabinete_dentario' => $row['gabinete_dentario'],
            'consultorio_medico' => $row['consultorio_medico'],
            'enfermaria' => $row['enfermaria'],
            'ambulatorio' => $row['ambulatorio'],
            'almoxarifado' => $row['almoxarifado'],
            'arquivo' => $row['arquivo'],
            'reprografia' => $row['reprografia'],
            'sala_gremio' => $row['sala_gremio'],
            'diretoria' => $row['diretoria'],
            'vicediretoria' => $row['vicediretoria'],
            'sala_prof' => $row['sala_prof'],
            'secretaria' => $row['secretaria'],
            'sala_orient_ed' => $row['sala_orient_ed'],
            'sala_coord_pedag' => $row['sala_coord_pedag'],
            'patio_coberto' => $row['patio_coberto'],
            'patio_descoberto' => $row['patio_descoberto'],
            'zeladoria' => $row['zeladoria'],
            'vestiario_fem' => $row['vestiario_fem'],
            'vestiario_masc' => $row['vestiario_masc'],
            'tot_vestiario' => $row['tot_vestiario'],
            'videoteca' => $row['videoteca'],
            'sala_tv' => $row['sala_tv'],
            'lab_info' => $row['lab_info'],
            'lab_ciencias' => $row['lab_ciencias'],
            'lab_fisica' => $row['lab_fisica'],
            'lab_quimica' => $row['lab_quimica'],
            'lab_biologia' => $row['lab_biologia'],
            'lab_ciencia_fisica_biologica' => $row['lab_ciencia_fisica_biologica'],
            'tot_lab_ciencia' => $row['tot_lab_ciencia'],
            'lab_linguas' => $row['lab_linguas'],
            'lab_multiuso' => $row['lab_multiuso'],
            'oficina' => $row['oficina'],
            'playground' => $row['playground'],
            'dormitorio' => $row['dormitorio'],
            'bercario' => $row['bercario'],
            'sanitario_adeq_pre' => $row['sanitario_adeq_pre'],
            'sanitario_adeq_pre_fem' => $row['sanitario_adeq_pre_fem'],
            'sanitario_adeq_pre_masc' => $row['sanitario_adeq_pre_masc'],
            'sanitario_adeq_def' => $row['sanitario_adeq_def'],
            'sanitario_adeq_def_fem' => $row['sanitario_adeq_def_fem'],
            'sanitario_adeq_def_masc' => $row['sanitario_adeq_def_masc'],
            'sanitario_al_masc' => $row['sanitario_al_masc'],
            'sanitario_al_fem' => $row['sanitario_al_fem'],
            'tot_sanitario_al' => $row['tot_sanitario_al'],
            'sanitario_func_fem' => $row['sanitario_func_fem'],
            'sanitario_func_masc' => $row['sanitario_func_masc'],
            'tot_sanitario_func' => $row['tot_sanitario_func'],
            'depend_adeq_def' => $row['depend_adeq_def'],
            'sala_ed_fisica' => $row['sala_ed_fisica'],
            'piscina' => $row['piscina'],
            'portaria' => $row['portaria'],
            'sala_prog_esc_familia' => $row['sala_prog_esc_familia'],
            'brinquedoteca' => $row['brinquedoteca'],
            'fraldario' => $row['fraldario'],
            'lactario' => $row['lactario'],
            'lavanderia' => $row['lavanderia'],
            'solario' => $row['solario'],
            'sala_espera' => $row['sala_espera'],
            'sala_inspetor' => $row['sala_inspetor'],
            'sala_reuniao' => $row['sala_reuniao'],
            'tesouraria' => $row['tesouraria'],
            'sala_reforco' => $row['sala_reforco'],
            'sala_diretor_tecnico' => $row['sala_diretor_tecnico'],
            'garagem_onibus' => $row['garagem_onibus'],
            'sala_fisioterapia' => $row['sala_fisioterapia'],
            'sala_psicologia' => $row['sala_psicologia'],
            'sala_fonoaudiologia' => $row['sala_fonoaudiologia'],
            'sala_eventos' => $row['sala_eventos'],
            'sala_assist_social' => $row['sala_assist_social'],
            'sala_terapia_educ' => $row['sala_terapia_educ'],
            'abatedouro' => $row['abatedouro'],
            'alojamento_fem' => $row['alojamento_fem'],
            'alojamento_masc' => $row['alojamento_masc'],
            'tot_alojamento' => $row['tot_alojamento'],
            'area_servico' => $row['area_servico'],
            'bazar' => $row['bazar'],
            'casa_maquina' => $row['casa_maquina'],
            'casa_func' => $row['casa_func'],
            'churrasqueira' => $row['churrasqueira'],
            'depositos_cereais' => $row['depositos_cereais'],
            'elevador' => $row['elevador'],
            'estacionamento' => $row['estacionamento'],
            'estufa' => $row['estufa'],
            'galpao_aves_corte' => $row['galpao_aves_corte'],
            'galpao_aves_postura' => $row['galpao_aves_postura'],
            'galpao_bovinos_leite' => $row['galpao_bovinos_leite'],
            'galpao_cunicultura' => $row['galpao_cunicultura'],
            'galpao_maq_agricola' => $row['galpao_maq_agricola'],
            'galpao_ovinos_caprinos' => $row['galpao_ovinos_caprinos'],
            'galpao_suino' => $row['galpao_suino'],
            'grafica' => $row['grafica'],
            'horta' => $row['horta'],
            'lab_didatica' => $row['lab_didatica'],
            'lab_junior' => $row['lab_junior'],
            'lab_enfermagem' => $row['lab_enfermagem'],
            'lab_estetica' => $row['lab_estetica'],
            'lab_psicopedagogia' => $row['lab_psicopedagogia'],
            'lab_turismo' => $row['lab_turismo'],
            'lavatorio' => $row['lavatorio'],
            'mangueira' => $row['mangueira'],
            'minhocario' => $row['minhocario'],
            'packing_house' => $row['packing_house'],
            'pomar' => $row['pomar'],
            'psicultura' => $row['psicultura'],
            'recepcao' => $row['recepcao'],
            'sala_atendimento' => $row['sala_atendimento'],
            'sala_atend_psicologico' => $row['sala_atend_psicologico'],
            'sala_aux_coordenacao' => $row['sala_aux_coordenacao'],
            'sala_dados' => $row['sala_dados'],
            'sala_dep_pessoal' => $row['sala_dep_pessoal'],
            'sala_ed_religiosa' => $row['sala_ed_religiosa'],
            'sala_energia_eletrica' => $row['sala_energia_eletrica'],
            'sala_entretenimento' => $row['sala_entretenimento'],
            'sala_estagio' => $row['sala_estagio'],
            'sala_ginastica' => $row['sala_ginastica'],
            'sala_insumo_agricola' => $row['sala_insumo_agricola'],
            'sala_insumo_veterinario' => $row['sala_insumo_veterinario'],
            'sala_marketing' => $row['sala_marketing'],
            'sala_matricula' => $row['sala_matricula'],
            'sala_musica' => $row['sala_musica'],
            'sala_pos_graduacao' => $row['sala_pos_graduacao'],
            'sala_ordenha' => $row['sala_ordenha'],
            'sala_proc_prod_agropecuarios' => $row['sala_proc_prod_agropecuarios'],
            'sala_seguranca' => $row['sala_seguranca'],
            'sala_telefonia' => $row['sala_telefonia'],
            'sala_financeiro' => $row['sala_financeiro'],
            'sala_pastoral' => $row['sala_pastoral'],
            'sala_reserv_agua' => $row['sala_reserv_agua'],
            'servidor' => $row['servidor'],
            'silo' => $row['silo'],
            'varanda' => $row['varanda'],
            'viveiro' => $row['viveiro'],
            'sala_reorg_neuro' => $row['sala_reorg_neuro'],
            'sala_terapia_ocup' => $row['sala_terapia_ocup'],
            'sala_serigrafia' => $row['sala_serigrafia'],
            'sala_marcenaria' => $row['sala_marcenaria'],
            'quiosque' => $row['quiosque']
        ]);
    }

    //Função para separar a importação por planilha e evitar lotação de memória
    public function chunkSize(): int
    {
        return 1000;
    }
}


?>